"""Public foundation contract exports."""

from veracrawl.contracts.agent import (
    AgentActionTrace,
    AgentRecommendation,
    AgentRunRequest,
    AgentRunResult,
    AgentRuntimeSpec,
    AgentToolSpec,
    ContextBundle,
    ContextBundleTrace,
    ContextRef,
    ModelCallTrace,
    ModelRequest,
    ModelResponse,
    ToolCallTrace,
)
from veracrawl.contracts.artifact import RuntimeArtifactRef
from veracrawl.contracts.browser import BrowserInteractionStep, BrowserSandboxPolicy
from veracrawl.contracts.command import (
    BaseCommandPayload,
    CommandEnvelope,
    CommandResult,
    CommandTypeSpec,
)
from veracrawl.contracts.durable import (
    DurableCommandRecord,
    DurableFixtureManifest,
    EventCursorRecord,
    OutboxRecord,
    UnitOfWorkRecord,
)
from veracrawl.contracts.event import CrawlRunEvent, EventCursor, EventTypeSpec
from veracrawl.contracts.evidence import (
    EvidenceAnchor,
    EvidenceCoverageResult,
    EvidencePacket,
    EvidencePacketManifest,
    EvidencePublicationFixtureManifest,
)
from veracrawl.contracts.fetch import DocumentArtifact, FetchAttempt, FetchResult, PageSnapshot
from veracrawl.contracts.fixture import (
    BenchmarkFixtureManifest,
    DRRestoreOracle,
    ExpectedEventSequenceOracle,
    ExpectedEvidenceCoverageOracle,
    ExpectedGraphOracle,
    ExpectedOutputOracle,
    FailureInjectionPlan,
    ReplayBundleOracle,
    ThresholdSpec,
)
from veracrawl.contracts.network import (
    NetworkAcquisitionReport,
    NetworkFixtureManifest,
    NetworkRequest,
    NetworkResponse,
    RedirectHop,
)
from veracrawl.contracts.objective import (
    CrawlObjective,
    CrawlPlan,
    CrawlRun,
    RunPlanSnapshot,
    RuntimeCompletionGate,
)
from veracrawl.contracts.policy import BlockedActionReport, PolicyDecision
from veracrawl.contracts.processing import (
    AnchorMap,
    ExtractionCandidate,
    ExtractionStrategy,
    LinkProvenance,
    NormalizationManifest,
    NormalizedDocument,
    NormalizeExtractReport,
    PageTypeClassification,
    ProcessFixtureManifest,
    SiteModel,
    TextAnchor,
)
from veracrawl.contracts.publication import OutputManifest, PublicationReport, PublishedOutput
from veracrawl.contracts.recovery import DurableReplayRecoveryReport
from veracrawl.contracts.registry import registry_json, validate_registry
from veracrawl.contracts.replay import ReplayBundleManifest, ReplayValidationReport
from veracrawl.contracts.scheduler import FrontierItem, QueueLease, SchedulerRecoveryReport
from veracrawl.contracts.source_adapter import (
    SourceAdapterCommand,
    SourceAdapterResult,
    SourceAdapterSpec,
)
from veracrawl.contracts.source_runtime import (
    RateLimitDecision,
    SourceAcquisitionReport,
    SourceFailureReport,
    SourceFixtureManifest,
)
from veracrawl.contracts.verification import ReviewDecision, VerificationDecision

__all__ = [
    "AgentActionTrace",
    "AgentRecommendation",
    "AgentRunRequest",
    "AgentRunResult",
    "AgentRuntimeSpec",
    "AgentToolSpec",
    "AnchorMap",
    "BaseCommandPayload",
    "BenchmarkFixtureManifest",
    "BlockedActionReport",
    "BrowserInteractionStep",
    "BrowserSandboxPolicy",
    "CommandEnvelope",
    "CommandResult",
    "CommandTypeSpec",
    "ContextBundle",
    "ContextBundleTrace",
    "ContextRef",
    "CrawlObjective",
    "CrawlPlan",
    "CrawlRun",
    "CrawlRunEvent",
    "DRRestoreOracle",
    "DocumentArtifact",
    "DurableCommandRecord",
    "DurableFixtureManifest",
    "DurableReplayRecoveryReport",
    "EventCursor",
    "EventCursorRecord",
    "EventTypeSpec",
    "ExpectedEventSequenceOracle",
    "ExpectedEvidenceCoverageOracle",
    "ExpectedGraphOracle",
    "ExpectedOutputOracle",
    "EvidenceCoverageResult",
    "EvidencePacket",
    "EvidenceAnchor",
    "EvidencePacketManifest",
    "EvidencePublicationFixtureManifest",
    "ExtractionCandidate",
    "ExtractionStrategy",
    "FetchAttempt",
    "FetchResult",
    "FailureInjectionPlan",
    "FrontierItem",
    "LinkProvenance",
    "ModelCallTrace",
    "ModelRequest",
    "ModelResponse",
    "NetworkAcquisitionReport",
    "NetworkFixtureManifest",
    "NetworkRequest",
    "NetworkResponse",
    "NormalizationManifest",
    "NormalizeExtractReport",
    "NormalizedDocument",
    "OutputManifest",
    "OutboxRecord",
    "PageSnapshot",
    "PageTypeClassification",
    "PolicyDecision",
    "ProcessFixtureManifest",
    "PublishedOutput",
    "PublicationReport",
    "QueueLease",
    "ReplayBundleManifest",
    "ReplayBundleOracle",
    "ReplayValidationReport",
    "RedirectHop",
    "RunPlanSnapshot",
    "RuntimeArtifactRef",
    "RuntimeCompletionGate",
    "SchedulerRecoveryReport",
    "RateLimitDecision",
    "ReviewDecision",
    "SiteModel",
    "SourceAcquisitionReport",
    "SourceAdapterCommand",
    "SourceAdapterResult",
    "SourceAdapterSpec",
    "SourceFailureReport",
    "SourceFixtureManifest",
    "ThresholdSpec",
    "TextAnchor",
    "ToolCallTrace",
    "UnitOfWorkRecord",
    "VerificationDecision",
    "registry_json",
    "validate_registry",
]
